### ISSUE TITLE
Support for Red Hat Linux

### ISSUE THREAD

**Issue by natebird** [zakird/wkhtmltopdf_binary_gem#104]
I ran into this issue today when I deployed up to a staging environment which is in Red Hat Linux and the gem installed fine but when the tests ran the library threw an error that the platform is not supported.

I'm willing to create a PR to add Red Hat Linux support if necessary. Is that needed or does anyone know of a workaround?

Thanks!

**Comment by natebird** [comment]
This article seems to show it can use the CentOS package. Hmm…

**Comment by pedrofurtado** [comment]
Hello, @natebird ! 👋 

Thanks for contact us.

Could you please write here what exactly was the error? The error message, maybe stack trace and so on 🤝 

Thanks a lot!

**Comment by natebird** [comment]
This was resolved with PR #105. Thanks!
