### ISSUE TITLE
Release of tags published in Rubygems, but not in Github repo yet

### ISSUE THREAD

**Issue by pedrofurtado** [zakird/wkhtmltopdf_binary_gem#113]
Hi, @unixmonkey ! 👋 🤓 

Only in order to maintain repo and rubygems synchronized, what do you think about create in repo the missing releases/tags, that are already published in rubygems but not in repo yet?

The versions are the list below:

- 0.12.6.5 - October 08, 2020
- 0.12.6.4 - September 15, 2020
- 0.12.6.3 - August 05, 2020
- 0.12.6.2 - June 29, 2020
- 0.12.6.1 - June 26, 2020
- 0.12.6 - June 15, 2020
- 0.12.5.4 - February 09, 2020

The latest tag created in repo, for a while, is 0.12.5.3 🤝 🍻

**Comment by unixmonkey** [comment]
Version `0.12.6.7` has just been published, and is currently up-to-date, and I've tagged all the above versions as best I could.

I will try to get better at tagging new gem versions every time I release. Thank you.
