### ISSUE TITLE
Support for Debian 11

### ISSUE THREAD

**Issue by shmokmt** [zakird/wkhtmltopdf_binary_gem#119]
Debian 11 was released.
https://www.debian.org/releases/bullseye/releasenotes

**Comment by shmokmt** [comment]
sorry, wkhtmltopdf itself doesn't seem to be stable in Debian 11.
https://wkhtmltopdf.org/downloads.html

**Comment by mcg** [comment]
What's the status of Debian 11 support? Ruby from Docker Hub is now based on it and https://github.com/wkhtmltopdf/packaging/issues/99 seems to show it's working.

**Comment by pedrofurtado** [comment]
@mcg  Once Debian 9 be supported officialy or at least working well on this distro, let us know that I create quickly a PR that adds this support for us 🤝 🍻
