### ISSUE TITLE
Update to Version 0.12.1

### ISSUE THREAD

**Issue by tadman** [zakird/wkhtmltopdf_binary_gem#13]
The [stable release](http://wkhtmltopdf.org/downloads.html) has been bumped to 0.12.1 and includes a number of important features. Is this a fairly straight-forward thing to build or is there a lot of leg-work involved?

The current release of this gem bundles 0.9.9 which dates from 2010.

**Comment by besi** [comment]
+1

**Comment by svoynow** [comment]
+1, let me know if there's anything I can do to help get this ready for a new rubygems version

**Comment by htatche** [comment]
So is it not enough to download the .pkg provided for OSX 64bit by the project and grab the binary from it ?

http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/wkhtmltox-0.12.2.1_osx-cocoa-x86-64.pkg

**Comment by unixmonkey** [comment]
Merged 0.12.3 in PR https://github.com/zakird/wkhtmltopdf_binary_gem/pull/31
