### ISSUE TITLE
wrong version on linux mint

### ISSUE THREAD

**Issue by cromega** [zakird/wkhtmltopdf_binary_gem#151]
I'm running Mint 21.1, which is based on ubuntu 22.04 but the os selector picks `ubuntu_18.04` for all linuxmint versions.

**Comment by unixmonkey** [comment]
Patches welcome.

**Comment by cromega** [comment]
Fair.

**Comment by unixmonkey** [comment]
This fix is now in version `0.12.6.7`. Please check it and make sure it works for you, and reopen if it doesn't. Thanks!
