### ISSUE TITLE
The current code version is behind rubygems

### ISSUE THREAD

**Issue by palytoxin** [zakird/wkhtmltopdf_binary_gem#157]
this code releases lastest is 0.12.5, but the rubygems is 0.12.6.5.
I have encountered some issues. would you push the lastest code?

**Comment by jeffbax** [comment]
Definitely get thrown off every time I come to this repo and see this a mismatch

**Comment by unixmonkey** [comment]
Version `0.12.6.7` has just been published, and is currently up-to-date.

My intent in the past has been to let the contributions sit on main for awhile so people can test and let me know if there's a problem before I publish, but in reality this doesn't happen as much as I thought it would, and it's probably better to just release it, and adjust if needed.

I will try to get better at releasing new gem versions every time I pull in a batch of contributions. Thank you.
