### ISSUE TITLE
Create README

### ISSUE THREAD

**Issue by butzopower** [zakird/wkhtmltopdf_binary_gem#16]
README should explain how to install gem, and what the binary's dependencies are depending on their distribution.

**Comment by icortex** [comment]
I want to use wkhtmltopdf on Heroku, but I don't understand what i have to do. Is it enough to copy the `wkhtmltopdf_linux_amd64` file in my Rails app bin folder? Thanks!

**Comment by ckarrie** [comment]
Same here, i don't know how to generate the binary for the RPi3 / Debian stretch. Please provide a short list of requirements (Ruby, etc.)

**Comment by unixmonkey** [comment]
There have been recent updates to the [README](https://github.com/zakird/wkhtmltopdf_binary_gem/blob/master/README) that I hope mostly address these concerns. Please let me know if it's still missing anything important.
