### ISSUE TITLE
Release to Rubygems

### ISSUE THREAD

**Issue by butzopower** [zakird/wkhtmltopdf_binary_gem#17]

**Comment by marnen** [comment]
+1. Can I help?

**Comment by bigtunacan** [comment]
It's been almost a year since this was opened; is anyone looking into this?

**Comment by toncid** [comment]
If you are using Heroku, I'd suggest switching to this: https://github.com/rafaelp/heroku-buildpack-wkhtmltopdf

**Comment by rposborne** [comment]
Or https://github.com/rposborne/wkhtmltopdf-heroku

**Comment by bigtunacan** [comment]
@toncid @rposborne I'm on company VMs.

**Comment by rietta** [comment]
Just ran into this with an older project today. It was a real head scratcher, digging down to running wkhtmltopdf at the command line to disable the quite flag and testing many images from HTTP and HTTPS sites to narrow down what was happening to cause it to fail silently.

Deploying from the master branch works; but it would be nice to see the updated build pushed to Rubygems.

**Comment by andyh** [comment]
I too have run into this same problem today with an older project. Can we get this pushed to rubygems?

**Comment by MichaelSp** [comment]
I'm just here to give my +1
Please, release asap.

**Comment by rposborne** [comment]
@bigtunacan no worries the heroku gem, is actually poorly named. It can run on any 14.04 ubuntu server. (we currently run it on our own bare metal)

**Comment by marnen** [comment]
This issue has been open for over a year. What is the holdup?

**Comment by DannyBen** [comment]
Why isn't this happening?
Both the repository and the owner seem to be active, but the gem is not released with the newer binaries.

I am using the [alternative edge fork][1] for now, but I am curious about the state of this gem and would prefer to use the canonical.

[1]: https://github.com/pallymore/wkhtmltopdf-binary-edge

**Comment by unixmonkey** [comment]
0.12.3 has been released to rubygems.org! Please open another issue if you have any problems.

**Comment by roolo** [comment]
@zakird @unixmonkey : Sooo…. We have 2016….

**Comment by roolo** [comment]
@unixmonkey Ty a lot
