### ISSUE TITLE
Does not work for ubuntu 20.04 arm64

### ISSUE THREAD

**Issue by edgardoburgos94** [zakird/wkhtmltopdf_binary_gem#170]
There isn't a `wkhtmltopdf_ubuntu_20.04_arm64.gz` file in the `bin` folder

**Comment by pargara** [comment]
@edgardoburgos94 You can fix this following this comment

https://github.com/zakird/wkhtmltopdf_binary_gem/issues/62#issuecomment-591801633

**Comment by unixmonkey** [comment]
Ubuntu 22.04 support is now in version `0.12.6.7`. Please check it and make sure it works for you, and reopen if it doesn't. Thanks!
