### ISSUE TITLE
Upgrade process and v1.2.2 pre release

### ISSUE THREAD

**Issue by jeroenj** [zakird/wkhtmltopdf_binary_gem#23]
The currently bundled version of wkhtmltopdf is [v1.2.1](https://github.com/zakird/wkhtmltopdf_binary_gem/commit/c4a244bc12e188fcf836f3f5a2cb457e70223e32). Since last week a lot of web hosts have disabled SSLv3 because of the [POODLE attack](http://en.wikipedia.org/wiki/POODLE).
wkhtmltopdf v1.2.1 (and earlier) still use SSLv3 by default. This has been changed in the current testing release ([v1.2.2.testing](http://wkhtmltopdf.org/downloads.html#testing)).

I was having a look to create a patch with the updated (testing) binaries so we could use this pre version in our app right now (since we rely on assets deliverd over https with SSLv3 disabled). Is there any good way to update the bundled binaries? It seems that the osx one can be extracted from the pkg, but I have no idea how to do that for the linux binaries. One option is to start a vagrant box for each required release and extract the binary from there but would that be enough? It would be nice if there was some more information on how to udpate the binaries.

**Comment by rietta** [comment]
Bundling from the master branch of this repo rather than the official Gem build seems to have fixed an issue with a PDF with images from Amazon S3 over SSL were not rendering. Due to a silent SSL failure with the older 0.9.9.3 build of wkhtmltopdf.

**Comment by unixmonkey** [comment]
0.12.3 has been merged in PR https://github.com/zakird/wkhtmltopdf_binary_gem/pull/31
