### ISSUE TITLE
Gem installation failing on AWS EC2 instance

### ISSUE THREAD

**Issue by ankur-1110** [zakird/wkhtmltopdf_binary_gem#24]
I am getting following error when during my application deployment on Amazon EC2. I tired upgrading the gem version to latest: 0.9.9.3. Still the same error persists. However, I could manually install the gem on EC2 instance using gem install command. Can you please confirm that this issue is related to AWS EC2 installation scripts alone? My other gems are installing fine though. 

---

Gem::RemoteFetcher::FetchError: bad response backend read error 503 (https://rubygems.global.ssl.fastly.net/gems/wkhtmltopdf-binary-0.9.9.1.gem)
An error occurred while installing wkhtmltopdf-binary (0.9.9.1), and Bundler
cannot continue.
Make sure that `gem install wkhtmltopdf-binary -v '0.9.9.1'` succeeds before
bundling.
ERROR: bundle install failed!

**Comment by unixmonkey** [comment]
0.9.x is a very old version at this point. I'm closing this issue for now. Please let me know if you are still having this issue.
