### ISSUE TITLE
Runtime error on Windows 7

### ISSUE THREAD

**Issue by abhishek77in** [zakird/wkhtmltopdf_binary_gem#25]
Error is happening when `render pdf: "pdf_name"` is called inside the controller.

```
RuntimeError at /reports/1/print
Bad wkhtmltopdf's path: bundler: command not found: which
Install missing gem executables with `bundle install`
```

Gems I am using - `rails 4.2`, `wkhtmltopdf-binary 0.9.9.3`, `wicked_pdf 0.11.0`. 
I have tried upgrading gem to latest version pointing to Github master branch but that doesn't help.

![wkhtmltopdf binary](https://cloud.githubusercontent.com/assets/749134/7166784/984a5e4a-e3cd-11e4-8b36-2c84aba63286.png)

**Comment by unixmonkey** [comment]
This is an issue for WickedPdf, and not wkhtmltopdf_binary_gem.

Set `:exe_path` to the full path including binary to `wkhtmltopdf` in `config/initializers/wicked_pdf.rb`
If this doesn't work for you, please open a new issue on that project and I'll take a closer look.

**Comment by abhishek77in** [comment]
@unixmonkey Sorry about raising the issue at wrong place. I am looking more into this issue will raise it in the correct place this time. Thanks.
