### ISSUE TITLE
Broken dependency on Heroku cedar-14 stack

### ISSUE THREAD

**Issue by joelcogen** [zakird/wkhtmltopdf_binary_gem#27]
Heroku moved from *libjpeg62* to *libjpeg8* with the new [cedar-14 stack](https://devcenter.heroku.com/articles/cedar-ubuntu-packages), which now breaks the binary:

    wkhtmltopdf_linux_amd64: error while loading shared libraries: libjpeg.so.62: cannot open shared object file: No such file or directory

On attempt I found at solving this issue: https://github.com/acdcorp/wkhtmltopdf_binary_gem/commit/d01271c34a889f2e0f5e07a8a4177043f8139c47

**Comment by pallymore** [comment]
Have you tried this gem? https://github.com/rposborne/wkhtmltopdf-heroku
