### ISSUE TITLE
nfs errors indirectly caused by wkhtmltopdf 

### ISSUE THREAD

**Issue by jimvanderveen** [zakird/wkhtmltopdf_binary_gem#38]
Our nfs server has been showing errors such as this:
```
rpc.mountd[2538]: authenticated mount request from OurNFSserver:864 for /homesrv/kalyptorisk.com (/homesrv)
rpc.mountd[2538]: can't stat exported dir /homesrv/kalyptorisk.com: No such file or directory
```
coming from servers using `wkhtmltopdf_binary_gem`. This is most likely an upstream problem from an earlier version of https://github.com/wkhtmltopdf/wkhtmltopdf -- It looks like it has been fixed in version 0.12.4

**Comment by jimvanderveen** [comment]
See also https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3401

**Comment by pedrofurtado** [comment]
I think this issue could also be closed, @unixmonkey 🤝

**Comment by pedrofurtado** [comment]
@unixmonkey I think we can close this issue 🤝
