### ISSUE TITLE
Not work in Alpine Linux

### ISSUE THREAD

**Issue by ducnguyenhuy** [zakird/wkhtmltopdf_binary_gem#42]
I'm using Docker image `ruby:2.4-alpine` and have installed this gem successful. I've found the binary files here `/bundle/gems/wkhtmltopdf-binary-0.12.3.1/bin` but when I try to cd to that path and enter `./wkhtmltopdf`, and nothing to show. And I tried to change to `Ubuntu` (Docker image ruby:2.4) and it worked by showing `Usage` for `wkhtmltopdf` with same steps above.

Could you please suggest me what I'm wrong? Thanks!

**Comment by unixmonkey** [comment]
As explained in #19, the Linux binaries are built against dynamically linked libraries, and you may need to install extra packages for `wkhtmltopdf` to work on your distribution.

Check that thread for suggestions, and if you get it working, please post what worked for you or didn't.

Good luck, and thanks for reaching out!
