### ISSUE TITLE
Update to latest version

### ISSUE THREAD

**Issue by rhuanbarreto** [zakird/wkhtmltopdf_binary_gem#44]
Hi! You need to update the wkhtmltopdf binary to the latest version!

**Comment by unixmonkey** [comment]
@rhuanbarreto Pull requests are appreciated and generally accepted!

**Comment by rhuanbarreto** [comment]
They didn't uploaded the binaries yet and I don't know how to build them 😢 . And there is already a pull request to update to 0.12.4 but unapproved.

**Comment by pedrofurtado** [comment]
I think this issue could be closed, @unixmonkey , since it is 2 years old in a old version too (0.12.4) 👍
