### ISSUE TITLE
How to bump binary version?

### ISSUE THREAD

**Issue by bibstha** [zakird/wkhtmltopdf_binary_gem#46]
From https://wkhtmltopdf.org/downloads.html I can see that OSX version comes in 32bit and 64bit `.pkg` and can be extracted from it.
For linux, there are individual files for ubuntu and debian 32 and 64 bit, and I guess we can extract the binary out of one?

Can someone write a script or instructions on how to extract these?
I can help with a PR for 0.12.5

**Comment by mileszs** [comment]
@unixmonkey @besi @bibstha I was going to update this, but there's an issue. It looks like the wkhtmltopdf project has decided to no longer include the compiled, generic binaries, based on their FAQ. Correct me if I'm mistaken in my conclusion, but it reads:

> **Where are the “generic” Linux builds?**
> The above binaries depend on packages provided by your distribution. Due to incompatibilities between library versions provided by each distribution, the only option is to use static linking – hence removed for now.

**Comment by unixmonkey** [comment]
@mileszs 0.12.4 had the same issue, and we released a "good enough" version that worked on at least Ubuntu-based linux systems based on the binaries provided, and I think that's what we are looking for here. This gem won't work for everyone, but should be a convenience for those who use an OS that binaries are available for.

**Comment by mileszs** [comment]
@unixmonkey Ah, cool. I will try to do that when I have the chance.

**Comment by joergschiller** [comment]
@unixmonkey maybe you can have a look at https://github.com/zakird/wkhtmltopdf_binary_gem/pull/49 - it might be more complete than https://github.com/zakird/wkhtmltopdf_binary_gem/pull/45

**Comment by pedrofurtado** [comment]
@unixmonkey @zakird @mileszs Any progress will be appreciated :handshake: :coffee: Anything we could help? Because I really don't know how to build this binary, in order to create myself a PR with this update :+1:

**Comment by unixmonkey** [comment]
Closing this because we have released 0.12.5 (and a few patch versions), so the process with new binaries is more straightforward now.
