### ISSUE TITLE
Wkhtmltopdf 0.12.5 - compile binaries

### ISSUE THREAD

**Issue by Laykou** [zakird/wkhtmltopdf_binary_gem#48]
Hi, are you please able to compile binaries also for the lastest wkhtmltopdf 0.12.5 version? Thank you

**Comment by soundasleep** [comment]
In the meantime there's another package for Ubuntu and OS X: https://github.com/pallymore/wkhtmltopdf-binary-edge

It would be ideal if the original gem could have the 0.12.5 binaries though! Thank you <3

**Comment by pedrofurtado** [comment]
@zakird 👍

**Comment by pedrofurtado** [comment]
@unixmonkey  👍 🥇

**Comment by unixmonkey** [comment]
0.12.5 has been released now. Please give it a try.
https://github.com/zakird/wkhtmltopdf_binary_gem/releases/tag/0.12.5
