### ISSUE TITLE
Syntax error: word unexpected (expecting ")")

### ISSUE THREAD

**Issue by pvin** [zakird/wkhtmltopdf_binary_gem#51]
In production server (ubuntu 14.04) getting this error

$ wkhtmltopdf http://www.google.com google.pdf

/usr/local/rvm/gems/ruby-2.5.1/gems/wkhtmltopdf-binary-0.12.4/bin/wkhtmltopdf_linux_x86: 1: /usr/local/rvm/gems/ruby-2.5.1/gems/wkhtmltopdf-binary-0.12.4/bin/wkhtmltopdf_linux_x86: Syntax error: word unexpected (expecting ")")

Any help? @zakird

**Comment by unixmonkey** [comment]
Are you still having this issue?

Does a newer release (current version is 0.12.5.2) have the same issue?

Please let me know what's happening if you can, but I'm closing this issue, since this is for an older version.
