### ISSUE TITLE
Adding binary into pure Ruby project

### ISSUE THREAD

**Issue by theasteve** [zakird/wkhtmltopdf_binary_gem#52]
I'm currently trying to make use of the `wicked_pdf` gem, however, I'm not using Rails. I installed the `/wkhtmltopdf_binary_gem` but still don't see any binary in the `bin` folder. Would it make sense to install this manually into `bin`?

<img width="289" alt="Screen Shot 2019-06-04 at 11 20 53 AM" src="https://user-images.githubusercontent.com/14843767/58891899-51bf2b00-86bb-11e9-8280-dba207e89b7e.png">
I'm using PDFtk, I can maybe download the binary into the folder manually. What is suggested in this case?

I see that the path is ```~/.rvm/gems/ruby-2.5.3/gems/wkhtmltopdf-binary-0.12.4/bin/wkhtmltopdf ``` should I set the executable path to this?

**Comment by unixmonkey** [comment]
When you install this gem, it copies a binstub into your rubygems bin directory; the same place other gem binaries get installed, and should be in your `$PATH`:

```
$ which wkhtmltopdf
~/.rvm/gems/ruby-2.5.3/bin/wkhtmltopdf
```

That binstub uses Ruby to find and execute the binary within this gem:
```
~/.rvm/gems/ruby-2.5.3/gems/wkhtmltopdf-binary-0.12.4/bin/wkhtmltopdf
```

And that file is also a binstub that checks your platform and picks out the real binary to execute.
You could theoretically copy the full binary from your path that you need, like: 

```
~/.rvm/gems/ruby-2.5.3/gems/wkhtmltopdf-binary-0.12.4/bin/wkhtmltopdf_linux_x86
```

into your `bin` directory alongside `pdftk` and rename it, but you could also shell out to it in your code with something like this:

```ruby
system("wkhtmltopdf #{options} #{input_file}.html #{output_file}.pdf")
```

and it should execute the right binary for the platform it's running on.

I hope that helps explain things a bit better.
Please let me know if you continue to have trouble.
