### ISSUE TITLE
Version 0.12.5 is not in repo

### ISSUE THREAD

**Issue by pedrofurtado** [zakird/wkhtmltopdf_binary_gem#54]
The version 0.12.5 is published in rubygems ( https://rubygems.org/gems/wkhtmltopdf-binary/versions/0.12.5 ) but it is not available in Github repo ( https://github.com/zakird/wkhtmltopdf_binary_gem/releases ) :+1:

**Comment by unixmonkey** [comment]
Thanks for noticing. Tagged and added to releases:
https://github.com/zakird/wkhtmltopdf_binary_gem/releases/tag/0.12.5
