### ISSUE TITLE
Please add support for  debian 10 (buster)

### ISSUE THREAD

**Issue by cob16** [zakird/wkhtmltopdf_binary_gem#58]
It would be nice to support Debian 10 as this is the latest stable since 6 July 2019.

This is now the default distro/version for the [official ruby images](
https://hub.docker.com/_/ruby) >= 2.6.5 to there is likely to be high demand as people update their dependencies in the coming weeks and months.

Happy to start a pr but I assume that only the maintainer/s are trusted to commit new binary files?

**Comment by simonini** [comment]
Hi! Is there some news or workaround about this?

**Comment by caljess599** [comment]
I have worked around this by downloading, extracting and placing the binary where it is being looked for. We are dockerized, so I don't know if this solution will work for you.
```
# Docker command to download and extract
RUN wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.buster_amd64.deb && mkdir wkhtml_work && dpkg -x wkhtmltox_0.12.5-1.buster_amd64.deb wkhtml_work && cp wkhtml_work/usr/local/bin/wk* /bin && rm -rf wkhtml_work && rm wkhtmltox_0.12.5-1.buster_amd64.deb

# add the missing .gz binary of wkhtmltopdf -- AFTER bundle install is run
RUN cp /bin/wkhtmltopdf /usr/local/bundle/ruby/2.6.0/gems/wkhtmltopdf-binary-0.12.5/bin/wkhtmltopdf_debian_10_amd64 && gzip --best /usr/local/bundle/ruby/2.6.0/gems/wkhtmltopdf-binary-0.12.5/bin/wkhtmltopdf_debian_10_amd64
```

**Comment by unixmonkey** [comment]
Version 0.12.5.1 has been pushed, which includes this change from #60 

Thank you all for your support and tips.

Please open a separate issue if you have any trouble with the new release.
