### ISSUE TITLE
Version 0.12.5.1 is not available in Github

### ISSUE THREAD

**Issue by pedrofurtado** [zakird/wkhtmltopdf_binary_gem#64]

**Comment by unixmonkey** [comment]
I just pushed tags for 0.12.5.1 and 0.12.5.2, both of which now show up at https://github.com/zakird/wkhtmltopdf_binary_gem/releases

I don't know if it's worth it to create real "releases" for every version though.
Isn't publishing the gem and tagging it enough?
What value do they have for you, if any?
