### ISSUE TITLE
libpng12 issues with latest linux system

### ISSUE THREAD

**Issue by faizaankhan** [zakird/wkhtmltopdf_binary_gem#72]
It's time libpng12 can be updated to libpng16.

**Comment by unixmonkey** [comment]
Could you please expand on this?

What's a good example OS and version for "latest linux system".

What is the issue you are seeing? Any error messages?

This project merely packages the official binaries, and doesn't build them or build `wkhtmltopdf`, and this is most certainly an upstream issue that should be taken up with https://github.com/wkhtmltopdf/wkhtmltopdf or https://github.com/wkhtmltopdf/packaging.

**Comment by faizaankhan** [comment]
libpng12 is available in ubuntu in latest up to 16. It's been made obsolete from 17 onwards. We can either upgrade libpng12 to libpng16 or provide information on the readme file. There's a lot of available places to download and install the older package but most ends up with some critical error. As of now PPA repository works best for 19.10. 

```
sudo add-apt-repository ppa:linuxuprising/libpng12
sudo apt update
sudo apt install libpng12-0
```
Anyone facing the same issue can refer above.

**Comment by equivalent** [comment]
above don't work for ubuntu 18.04 ^^^

i

**Comment by pedrofurtado** [comment]
It not appears to be related with gem itself. Maybe we can close it, @unixmonkey 🍻
