### ISSUE TITLE
Missing Support for Oracle Linux 7.8

### ISSUE THREAD

**Issue by victorsh-crn** [zakird/wkhtmltopdf_binary_gem#79]
Hello!

I'm trying to install Wkhtmltopdf on an Oracle Linux 7.8 (Fedora) Docker Container. After running
```
yum install xvfb -y
yum install libfontconfig -y
yum install wkhtmltopdf -y
```
Everything install fine. But then when I got to test wkhtmltopdf with `wkhtmltopdf http://google.com google.pdf` I get a runtime error.
```
/opt/app/vendor/bundle/ruby/2.6.0/gems/wkhtmltopdf-binary-0.12.5.4/bin/wkhtmltopdf:45:in `<top (required)>': Invalid platform, must be running on Ubuntu 14.04/16.04/18.04 CentOS 6/7/8, Debian 8/9/10, or intel-based macOS (missing binary: /opt/app/vendor/bundle/ruby/2.6.0/gems/wkhtmltopdf-binary-0.12.5.4/bin/wkhtmltopdf_ol_7.8_amd64). (RuntimeError)
```

Details on OS
```
NAME="Oracle Linux Server"
VERSION="7.8"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.8"
PRETTY_NAME="Oracle Linux Server 7.8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:8:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.8
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.8
```

**Comment by pedrofurtado** [comment]
@victorsh-crn I am not familiar with Oracle Linux. Is that a OS based in some official supported OS by wkhtmltopdf. CentOS 6/7/8 are supported by wkhtmltopdf.
If Oracle Linux 7.8 is based on any of the 3 that I mentioned, let us know then we can add the mapping in gem 👍 
If not, I think the error could be related in fact that this OS is not supported by wkhtmltopdf.

**Comment by pedrofurtado** [comment]
@unixmonkey Maybe we can close this issue 🤝
