### ISSUE TITLE
Can a binary for ubuntu 20.04 be added?

### ISSUE THREAD

**Issue by johnjin0000** [zakird/wkhtmltopdf_binary_gem#82]
I'm getting an error that says:

Invalid platform, must be running on Ubuntu 16.04/18.04/20.04 CentOS 6/7/8, Debian 9/10, or intel-based Cocoa macOS (missing binary: /home/johnjin0000/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/wkhtmltopdf-binary-0.12.6/bin/wkhtmltopdf_ubuntu_20.04_amd64)

But I am using an ubuntu 20.04 machine, so it would be nice if a binary for 20.04 can be added

**Comment by alaarab** [comment]
It definitely needs a 20.04 binary added. I get the same issue in 20.04 ubuntu.

**Comment by andrecavallari** [comment]
https://github.com/zakird/wkhtmltopdf_binary_gem/blob/master/CHANGELOG

But it seems they forgot to add the 20.04 binaries

**Comment by unixmonkey** [comment]
This is now published to version `0.12.6.1` of the gem.
