### ISSUE TITLE
Error with 0.12.6 Binary.

### ISSUE THREAD

**Issue by acha5066** [zakird/wkhtmltopdf_binary_gem#91]
I'm hosting a website on PlatformSH which uses this gem to install the appropriate binary. It was updated to 0.12.6 and suddenly I got this error message:

```
Error generating document: Failed to generate PDF: /app/.global/gems/wkhtmltopdf-binary-0.12.6/bin/wkhtmltopdf:28:in `': undefined method `match?' for /deepin/:Regexp (NoMethodError) Did you mean? match from /app/.global/bin/wkhtmltopdf:22:in `load' from /app/.global/bin/wkhtmltopdf:22:in `'
```

No other code was changed apart from the binary version. I'm using a Drupal module called entity_print that uses the library phpwkhtmltopdf but the maintainer of that library did not think the issue was in that library but likely related to this gem.

Reverting to 0.12.5.4 fixed it for me.

**Comment by unixmonkey** [comment]
It appears that `Regexp#match?` showed up in Ruby 2.4, so you might want to update if possible, but I'm open to changing things to use `Regexp#match`, which would work just as well in this context on older versions of Ruby.

**Comment by ahtesham78** [comment]
@acha5066 this issue is now fixed in the latest master.
https://github.com/zakird/wkhtmltopdf_binary_gem/pull/95

**Comment by T2L** [comment]
@unixmonkey could we have a new release with the updates from #95 ? Thanks

**Comment by pedrofurtado** [comment]
Thanks for pull request, @ahteshamtariq ! 🍻 

@unixmonkey , problem solved for older rubies, I think we can close it 🎉
