### ISSUE TITLE
The binary for debian 9 is never selected?

### ISSUE THREAD

**Issue by johnny-miyake** [zakird/wkhtmltopdf_binary_gem#98]
This commit brakes my app.
https://github.com/zakird/wkhtmltopdf_binary_gem/commit/dbc932143d08b8236dc54157d8331edb9481e197

I have been using wkhtmltopdf-binary on Debian 9 for a couple of years on my projects. Recently I updated the gem from 0.16.3 to 0.16.4, then I got the following error.

```
$ /usr/local/bundle/bin/wkhtmltopdf --quiet --page-size A4 --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 --enable-local-file-access - -
/usr/local/bundle/gems/wkhtmltopdf-binary-0.12.6.4/bin/wkhtmltopdf_debian_10_amd64: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /usr/local/bundle/gems/wkhtmltopdf-binary-0.12.6.4/bin/wkhtmltopdf_debian_10_amd64)
/usr/local/bundle/gems/wkhtmltopdf-binary-0.12.6.4/bin/wkhtmltopdf_debian_10_amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/local/bundle/gems/wkhtmltopdf-binary-0.12.6.4/bin/wkhtmltopdf_debian_10_amd64)
```

It seems that the additional lines in the commit selects the binary for debian 10 instead of the one for debian 9 by overwriting `os` variable. For an experiment, I deleted the additional lines and ran the command, then it worked.

### My OS
```sh
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by unixmonkey** [comment]
Thanks for pointing this out.

Can you tell me what this outputs for you?

```ruby
require 'rbconfig'
puts RbConfig::CONFIG['host_os']
```

A pull request to fix this would be welcomed, ideally working for both Debian 9 and 10.

**Comment by johnny-miyake** [comment]
The code resulted in this output.
```ruby
linux-gnu
```

**Comment by unixmonkey** [comment]
Oh, I'm so sorry, I meant to ask for what populates `os`, not `suffix`, but got it mixed up. I see what it would be from your post though.

I think an appropriate patch would look like this:
```ruby
os_based_on_debian_9 =  (/(debian_9|deepin)/ =~ os)
```

**Comment by johnny-miyake** [comment]
Thanks for your suggestion.

Here is what I found about `os` when I ran the code.

L15 assigns `'debian_9'` to `os`.
https://github.com/zakird/wkhtmltopdf_binary_gem/blob/dbc932143d08b8236dc54157d8331edb9481e197/bin/wkhtmltopdf#L15

L32-33 does nothing because `'debian_9'` does not match `(/deepin/ =~ os)`. `os_based_on_debian_9` remains `nil`.  (The patch you suggested would make the code more readable.)
https://github.com/zakird/wkhtmltopdf_binary_gem/blob/dbc932143d08b8236dc54157d8331edb9481e197/bin/wkhtmltopdf#L32-L33

L35-36 overwrites `os` by `'debian_10'` because `'debian_9'` matches `os.start_with?('debian')`.
https://github.com/zakird/wkhtmltopdf_binary_gem/blob/dbc932143d08b8236dc54157d8331edb9481e197/bin/wkhtmltopdf#L35-L36

Therefore I think L35 should be like this so that it ignores `"debian_9"`.
```ruby
os_based_on_debian = !os_based_on_debian_9 && os.start_with?('debian')
```

**Comment by johnny-miyake** [comment]
I created a pull request for this issue.
https://github.com/zakird/wkhtmltopdf_binary_gem/pull/99

**Comment by unixmonkey** [comment]
This is now in version 0.12.6.5. Please let me know if you have any issues. Thanks again!
